# volumes:
services:
  fastapi:
    environment:
      DATABASE_URL: ${DATABASE_URL_FROM_ENV_FILE}
      SIGNING_KEY: ${SIGNING_KEY_FROM_ENV_FILE}
      CORS_HOST: http://localhost:5173
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    # user: "501:20" # on macOS and Linux, replace this with your real user id and group id
    volumes:
      - ./api:/app

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    volumes:
      - pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: 1

  postgres:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres-data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    # user: "501:20" # on macOS and Linux, replace this with your real user id and group id
    ports:
      - "5173:5173"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      VITE_API_HOST: ${VITE_API_HOST}

volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true
